# Set the path of your corpus
# "/mnt/home/xungong-andr-1766e0/downloads/" means the corpus can be downloaded by the recipe automatically

ACCENTED_FR=/mnt/home/xungong-andr-1766e0/downloads/
ACCENT_DB=
ACESINGER=/mnt/home/xungong-andr-1766e0/downloads/
AIDATATANG_200ZH=/mnt/home/xungong-andr-1766e0/downloads/
AISHELL=/mnt/home/xungong-andr-1766e0/downloads/
AISHELL2=
AISHELL3=/mnt/home/xungong-andr-1766e0/downloads/
AISHELL4=/mnt/home/xungong-andr-1766e0/downloads/
ALFFA=/mnt/home/xungong-andr-1766e0/downloads/
ALLSSTAR_ENG=/mnt/home/xungong-andr-1766e0/downloads/
AMERICASNLP22=/mnt/home/xungong-andr-1766e0/downloads/
AN4=/mnt/home/xungong-andr-1766e0/downloads/
ASVTutorial=espnet_tutorial_asvspoof
APHASIABANK=
AR_SC=
AUDIOSET=/mnt/home/xungong-andr-1766e0/downloads/
ASVSpoof_CMD=
BIBLETTS=/mnt/home/xungong-andr-1766e0/downloads/
CORAAL=/mnt/home/xungong-andr-1766e0/downloads/
COVOST2=
DIRHA_ENGLISH_PHDEV=
DIRHA_WSJ=
DIRHA_WSJ_PROCESSED="${PWD}/data/local/dirha_wsj_processed"  # Output file path
DNS=
DNS2=
DNS3=
DNS4=/mnt/home/xungong-andr-1766e0/downloads/
DSING=/mnt/home/xungong-andr-1766e0/downloads/
ESC50=
WSJ0=
WSJ1=
WSJ0_2MIX= # Path to wsj0_mix directory
WSJCAM0=
WSJ_KINECT=
REAZONSPEECH=/mnt/home/xungong-andr-1766e0/downloads/
REVERB=
REVERB_OUT="${PWD}/REVERB"  # Output file path
CHIME1=
CHIME2_WSJ0=
CHIME2_GRID=
CHIME3=
CHIME4=
CHIME5= # Path to CHiME5/audio directory
CSJDATATOP=
CSJVER=dvd  ## Set your CSJ format (dvd or usb).
            ## Usage    :
            ## Case DVD : We assume CSJ DVDs are copied in this directory with the names dvd1, dvd2,...,dvd17.
            ##            Necessary directory is dvd3 - dvd17.
            ##            e.g. $ ls $CSJDATATOP(DVD) => 00README.txt dvd1 dvd2 ... dvd17
            ##
            ## Case USB : Necessary directory is MORPH/SDB and WAV
            ##            e.g. $ ls $CSJDATATOP(USB) => 00README.txt DOC MORPH ... WAV fileList.csv
            ## Case merl :MERL setup. Necessary directory is WAV and sdb
CSMSC=/mnt/home/xungong-andr-1766e0/downloads/
CSS10=
DIHARD2= # Path to dihard2/second_dihard_challenge_dev-eleven_srcs/data/multichannel/sad directory
GENSHIN=/mnt/home/xungong-andr-1766e0/downloads/
HKUST1=
HKUST2=
HUI_ACG=/mnt/home/xungong-andr-1766e0/downloads/
HUB4_SPANISH=
LABOROTV=
TEDXJP=
LIBRISPEECH=/mnt/home/xungong-andr-1766e0/downloads/LibriSpeech/
LIBRILIGHT_LIMITED=
LIBRILIGHT=/mnt/home/xungong-andr-1766e0/downloads/
FSC=
FREESOUND=
MELD=/mnt/home/xungong-andr-1766e0/downloads/
SLURP=
SLURP_S= # Output file path
LIBRITRANS_S= # Output file path
VOICES=/mnt/home/xungong-andr-1766e0/downloads/
MAGICDATA=/mnt/home/xungong-andr-1766e0/downloads/
MEDIASPEECH=/mnt/home/xungong-andr-1766e0/downloads/
MINI_LIBRISPEECH=/mnt/home/xungong-andr-1766e0/downloads/
MISP2021=
MLSUPERB=
L3DAS22=
LIBRIMIX=/mnt/home/xungong-andr-1766e0/downloads/
LIBRITTS=/mnt/home/xungong-andr-1766e0/downloads/
LIBRITTS_R=/mnt/home/xungong-andr-1766e0/downloads/
LJSPEECH=/mnt/home/xungong-andr-1766e0/downloads/
LT_SPEECH_CMD=
MUSAN=
MUSDB18=/mnt/home/xungong-andr-1766e0/downloads/
MUST_C=/mnt/home/xungong-andr-1766e0/downloads/
MUSTARD=
MUSTARD_PLUS=
NSC=
MYST=/mnt/home/xungong-andr-1766e0/downloads/
NIT_SONG070=
JMD=/mnt/home/xungong-andr-1766e0/downloads/
JSSS=/mnt/home/xungong-andr-1766e0/downloads/
JSUT=/mnt/home/xungong-andr-1766e0/downloads/
JSUT_SONG=
JTUBESPEECH=/mnt/home/xungong-andr-1766e0/downloads/
JVS=/mnt/home/xungong-andr-1766e0/downloads/
KISING=/mnt/home/xungong-andr-1766e0/downloads/
KSC=/mnt/home/xungong-andr-1766e0/downloads/
KSS=
QASR_TTS=/mnt/home/xungong-andr-1766e0/downloads/
SNIPS= # smart-light-en-closed-field data path
SPGISPEECH=
SPEECH_PROMPT_v2=
STOP=
SWBD=
FISHER_CALLHOME_SPANISH=
SWBD_NXT=
THCHS30=/mnt/home/xungong-andr-1766e0/downloads/
TIMIT=
TSUKUYOMI=/mnt/home/xungong-andr-1766e0/downloads/
VOXFORGE=/mnt/home/xungong-andr-1766e0/downloads/
AMI=
COMMONVOICE=/mnt/home/xungong-andr-1766e0/downloads/
CVSS=
FLEURS=/mnt/home/xungong-andr-1766e0/downloads/
MICROSOFT_SPEECH_CORPUS=
EASYCOM=
BABEL_101=
BABEL_102=
BABEL_103=
BABEL_104=
BABEL_105=
BABEL_106=
BABEL_107=
BABEL_201=
BABEL_202=
BABEL_203=
BABEL_204=
BABEL_205=
BABEL_206=
BABEL_207=
BABEL_301=
BABEL_302=
BABEL_303=
BABEL_304=
BABEL_305=
BABEL_306=
BABEL_307=
BABEL_401=
BABEL_402=
BABEL_403=
BABEL_404=
PUEBLA_NAHUATL=/mnt/home/xungong-andr-1766e0/downloads/
TEDLIUM2=/mnt/home/xungong-andr-1766e0/downloads/
TEDLIUM3=/mnt/home/xungong-andr-1766e0/downloads/
VCTK=/mnt/home/xungong-andr-1766e0/downloads/
VIVOS=/mnt/home/xungong-andr-1766e0/downloads/
YESNO=/mnt/home/xungong-andr-1766e0/downloads/
YOLOXOCHITL_MIXTEC=/mnt/home/xungong-andr-1766e0/downloads/
HOW2_TEXT=/mnt/home/xungong-andr-1766e0/downloads//how2-300h-v1
HOW2_FEATS=/mnt/home/xungong-andr-1766e0/downloads//fbank_pitch_181516
HOW2_2kH=/mnt/home/xungong-andr-1766e0/downloads//how2_release
ZEROTH_KOREAN=/mnt/home/xungong-andr-1766e0/downloads/
JAVA=/mnt/home/xungong-andr-1766e0/downloads/
RU_OPEN_STT=/mnt/home/xungong-andr-1766e0/downloads/
RUSLAN=/mnt/home/xungong-andr-1766e0/downloads/
SIWIS=/mnt/home/xungong-andr-1766e0/downloads/
GIGASPEECH=
GIGAST=
GOOGLEI18N=/mnt/home/xungong-andr-1766e0/downloads/
NOISY_SPEECH=
NOISY_REVERBERANT_SPEECH=
LRS2=
LRS3=
SUNDA=/mnt/home/xungong-andr-1766e0/downloads/
CMU_ARCTIC=/mnt/home/xungong-andr-1766e0/downloads/
CMU_INDIC=/mnt/home/xungong-andr-1766e0/downloads/
INDIC_SPEECH=/mnt/home/xungong-andr-1766e0/downloads/
IWSLT22_DIALECT=
IWSLT22_LOW_RESOURCE=/mnt/home/xungong-andr-1766e0/downloads/
IWSLT24_INDIC=
JKAC=
MUCS_SUBTASK1=/mnt/home/xungong-andr-1766e0/downloads/
MUCS_SUBTASK2=/mnt/home/xungong-andr-1766e0/downloads/
GAMAYUN=/mnt/home/xungong-andr-1766e0/downloads/
IWSLT21LR=/mnt/home/xungong-andr-1766e0/downloads//iwslt21
JDCINAL=/mnt/home/xungong-andr-1766e0/downloads/
GRABO=/mnt/home/xungong-andr-1766e0/downloads/
WENETSPEECH=
SPEECHCOMMANDS=/mnt/home/xungong-andr-1766e0/downloads/
TOTONAC=/mnt/home/xungong-andr-1766e0/downloads/
PRIMEWORDS_CHINESE=/mnt/home/xungong-andr-1766e0/downloads/
SEAME=
BENGALI=/mnt/home/xungong-andr-1766e0/downloads/
IWSLT14=
BURMESE=/mnt/home/xungong-andr-1766e0/downloads/
MALAYALAM=/mnt/home/xungong-andr-1766e0/downloads/
ST_CMDS=/mnt/home/xungong-andr-1766e0/downloads/
MS_INDIC_IS18=
MARATHI=/mnt/home/xungong-andr-1766e0/downloads/
MLS=/mnt/home/xungong-andr-1766e0/downloads/
VOXPOPULI=/mnt/home/xungong-andr-1766e0/downloads/
HARPERVALLEY=/mnt/home/xungong-andr-1766e0/downloads/
TALROMUR=/mnt/home/xungong-andr-1766e0/downloads/
TALROMUR2=/mnt/home/xungong-andr-1766e0/downloads/
DCASE=
TEDX_SPANISH=/mnt/home/xungong-andr-1766e0/downloads/
IAM=/mnt/home/xungong-andr-1766e0/downloads/
IBAN=
OFUTON=
OGI_KIDS_SPEECH=
OPENCPOP=
M_AILABS=/mnt/home/xungong-andr-1766e0/downloads/
CATSLU=/mnt/home/xungong-andr-1766e0/downloads/
ELRA_E0024=
ELRA_S0272=
ELRA_S0371=
M4SINGER=
ONIKU=
PJS=
AMABOSHI=
ITAKO=
NATSUME=
KIRITAN=
NAMINE=
KATHBATH=/mnt/home/xungong-andr-1766e0/downloads/
GRAMVAANI=/mnt/home/xungong-andr-1766e0/downloads/
SPRING_INX=/mnt/home/xungong-andr-1766e0/downloads/
VOXCELEB=
KSPONSPEECH=
HIFITTS=/mnt/home/xungong-andr-1766e0/downloads/
CLOTHO_V2=/mnt/home/xungong-andr-1766e0/downloads/
AUDIOCAPS=
CLOTHO_CHATGPT_MIXUP=
EDACC=/mnt/home/xungong-andr-1766e0/downloads/
IPAPACK_PLUS=/mnt/home/xungong-andr-1766e0/downloads/
GALAXY=


# For only CMU TIR environment
if [[ "$(hostname)" == tir* ]]; then
    BABEL_101=/projects/tir5/data/speech_corpora/babel/IARPA_BABEL_BP_101/
    BABEL_102=/projects/tir5/data/speech_corpora/babel/BABEL_OP1_102/
    BABEL_103=/projects/tir5/data/speech_corpora/babel/BABEL_OP1_103/
    BABEL_104=/projects/tir5/data/speech_corpora/babel/BABEL_BP_104/
    BABEL_105=/projects/tir5/data/speech_corpora/babel/IARPA-babel105b-v0.5-build/BABEL_BP_105/
    BABEL_106=/projects/tir5/data/speech_corpora/babel/BABEL_BP_106/
    BABEL_107=/projects/tir5/data/speech_corpora/babel/BABEL_BP_107/
    BABEL_201=/projects/tir5/data/speech_corpora/babel/IARPA-babel201b-v0.2b.build/BABEL_OP1_201/
    BABEL_202=/projects/tir5/data/speech_corpora/babel/IARPA-babel202b-v1.0d-build/BABEL_OP2_202/
    BABEL_203=/projects/tir5/data/speech_corpora/babel/IARPA-babel203b-v3.1a-build/
    BABEL_204=/projects/tir5/data/speech_corpora/babel/BABEL_OP1_204/
    BABEL_205=/projects/tir5/data/speech_corpora/babel/IARPA-babel205b-v1.0a-build/BABEL_OP2_205/
    BABEL_206=/projects/tir5/data/speech_corpora/babel/BABEL_OP1_206/
    BABEL_207=/projects/tir5/data/speech_corpora/babel/IARPA-babel207b-v1.0e-build/BABEL_OP2_207/
    BABEL_301=/projects/tir5/data/speech_corpora/babel/IARPA-babel301b-v2.0b-build/BABEL_OP2_301/
    BABEL_302=/projects/tir5/data/speech_corpora/babel/IARPA-babel302b-v1.0a-build/BABEL_OP2_302/
    BABEL_303=/projects/tir5/data/speech_corpora/babel/IARPA-babel303b-v1.0a/BABEL_OP2_303/
    BABEL_304=/projects/tir5/data/speech_corpora/babel/IARPA-babel304b-v1.0b/BABEL_OP2_304/
    BABEL_305=/projects/tir5/data/speech_corpora/babel/IARPA-babel305b-v1.0c-build/BABEL_OP3_305/
    BABEL_306=/projects/tir5/data/speech_corpora/babel/IARPA-babel306b-v2.0c-build/BABEL_OP3_306/
    BABEL_307=/projects/tir5/data/speech_corpora/babel/IARPA-babel307b-v1.0b-build/BABEL_OP3_307/
    BABEL_401=/projects/tir5/data/speech_corpora/babel/IARPA-babel401b-v2.0b-build/BABEL_OP3_401/
    BABEL_402=/projects/tir5/data/speech_corpora/babel/IARPA-babel402b-v1.0b-build/BABEL_OP3_402/
    BABEL_403=/projects/tir5/data/speech_corpora/babel/IARPA-babel403b-v1.0b-build/BABEL_OP3_403/
    BABEL_404=/projects/tir5/data/speech_corpora/babel/IARPA_BABEL_OP3_404/
    GRABO=/projects/tir5/data/speech_corpora/Grabo
    IWSLT14=/projects/tir5/data/iwslt14
    IWSLT22_DIALECT=/projects/tir5/data/speech_corpora/LDC2022E01_IWSLT22_Tunisian_Arabic_Shared_Task_Training_Data/
    PRIMEWORDS_CHINESE=/projects/tir5/data/speech_corpora/Primewords_Chinese
    FISHER_CALLHOME_SPANISH=/projects/tir5/data/speech_corpora/fisher_callhome_spanish
    DSING=/projects/tir5/data/speech_corpora/sing_300x30x2
    MS_INDIC_IS18=/projects/tir6/general/cnariset/corpora/microsoft_speech_corpus_indian_languages
    AISHELL=/projects/tir5/data/speech_corpora/Aishell
    LIBRISPEECH=/projects/tir5/data/speech_corpora/LibriSpeech
    SLURP=/projects/tir5/data/speech_corpora/SLURP
fi

# For only JHU environment
if [[ "$(hostname -d)" == clsp.jhu.edu ]]; then
    AIDATATANG_200ZH=/mnt/home/xungong-andr-1766e0/downloads/
    AISHELL=
    AISHELL3=/mnt/home/xungong-andr-1766e0/downloads/
    ALFFA=/mnt/home/xungong-andr-1766e0/downloads/
    AN4=
    DIRHA_ENGLISH_PHDEV=
    DIRHA_WSJ=
    DIRHA_WSJ_PROCESSED="${PWD}/data/local/dirha_wsj_processed"  # Output file path
    DNS=
    WSJ0=
    WSJ1=
    WSJCAM0=/export/corpora3/LDC/LDC95S24/wsjcam0
    REVERB=/export/corpora5/REVERB_2014/REVERB
    REVERB_OUT="${PWD}/REVERB"  # Output file path
    CHIME3=
    CHIME4=
    CSJDATATOP=/export/corpora5/CSJ/USB
    CSJVER=usb  ## Set your CSJ format (dvd or usb).
                ## Usage    :
                ## Case DVD : We assume CSJ DVDs are copied in this directory with the names dvd1, dvd2,...,dvd17.
                ##            Necessary directory is dvd3 - dvd17.
                ##            e.g. $ ls $CSJDATATOP(DVD) => 00README.txt dvd1 dvd2 ... dvd17
                ##
                ## Case USB : Necessary directory is MORPH/SDB and WAV
                ##            e.g. $ ls $CSJDATATOP(USB) => 00README.txt DOC MORPH ... WAV fileList.csv
                ## Case merl :MERL setup. Necessary directory is WAV and sdb
    CSMSC=/mnt/home/xungong-andr-1766e0/downloads/
    CSS10=
    HKUST1=
    HKUST2=
    HUI_ACG=/mnt/home/xungong-andr-1766e0/downloads/
    HUB4_SPANISH=
    LABOROTV=
    TEDXJP=
    LIBRISPEECH=
    FSC=
    SNIPS= # smart-light-en-closed-field data path
    SLURP=
    MEDIASPEECH=/mnt/home/xungong-andr-1766e0/downloads/
    MINI_LIBRISPEECH=/mnt/home/xungong-andr-1766e0/downloads/
    LIBRITTS=
    LJSPEECH=/mnt/home/xungong-andr-1766e0/downloads/
    JMD=/mnt/home/xungong-andr-1766e0/downloads/
    JSSS=/mnt/home/xungong-andr-1766e0/downloads/
    JSUT=/mnt/home/xungong-andr-1766e0/downloads/
    JVS=/mnt/home/xungong-andr-1766e0/downloads/
    KSS=
    THCHS30=/mnt/home/xungong-andr-1766e0/downloads/
    TIMIT=
    TSUKUYOMI=/mnt/home/xungong-andr-1766e0/downloads/
    VOXFORGE=
    AMI=/export/corpora4/ami/amicorpus
    COMMONVOICE=/mnt/home/xungong-andr-1766e0/downloads/
    BABEL_101=/export/babel/data/101-cantonese
    BABEL_102=/export/babel/data/102-assamese
    BABEL_103=/export/babel/data/103-bengali
    BABEL_104=/export/babel/data/104-pashto
    BABEL_105=/export/babel/data/105-turkish
    BABEL_106=/export/babel/data/106-tagalog
    BABEL_107=/export/babel/data/107-vietnamese
    BABEL_201=/export/babel/data/201-haitian
    BABEL_202=/export/babel/data/202-swahili/IARPA-babel202b-v1.0d-build/BABEL_OP2_202
    BABEL_203=/export/babel/data/203-lao
    BABEL_204=/export/babel/data/204-tamil
    BABEL_205=/export/babel/data/205-kurmanji/IARPA-babel205b-v1.0a-build/BABEL_OP2_205
    BABEL_206=/export/babel/data/206-zulu
    BABEL_207=/export/babel/data/207-tokpisin/IARPA-babel207b-v1.0e-build/BABEL_OP2_207
    BABEL_301=/export/babel/data/301-cebuano/IARPA-babel301b-v2.0b-build/BABEL_OP2_301
    BABEL_302=/export/babel/data/302-kazakh/IARPA-babel302b-v1.0a-build/BABEL_OP2_302
    BABEL_303=/export/babel/data/303-telugu/IARPA-babel303b-v1.0a-build/BABEL_OP2_303
    BABEL_304=/export/babel/data/304-lithuanian/IARPA-babel304b-v1.0b-build/BABEL_OP2_304
    BABEL_305=/export/babel/data/305-guarani/IARPA-babel305b-v1.0b-build/BABEL_OP3_305
    BABEL_306=/export/babel/data/306-igbo/IARPA-babel306b-v2.0c-build/BABEL_OP3_306
    BABEL_307=/export/babel/data/307-amharic/IARPA-babel307b-v1.0b-build/BABEL_OP3_307
    BABEL_401=/export/babel/data/401-mongolian/IARPA-babel401b-v2.0b-build/BABEL_OP3_401
    BABEL_402=/export/babel/data/402-javanese/IARPA-babel402b-v1.0b-build/BABEL_OP3_402
    BABEL_403=/export/babel/data/403-dholuo/IARPA-babel403b-v1.0b-build/BABEL_OP3_403
    BABEL_404=/export/corpora/LDC/LDC2016S12/IARPA_BABEL_OP3_404
    PUEBLA_NAHUATL=
    TEDLIUM2=/mnt/home/xungong-andr-1766e0/downloads/
    TEDLIUM3=/mnt/home/xungong-andr-1766e0/downloads/
    VCTK=/mnt/home/xungong-andr-1766e0/downloads/
    VIVOS=
    YESNO=
    YOLOXOCHITL_MIXTEC=/mnt/home/xungong-andr-1766e0/downloads/
    HOW2_TEXT=
    HOW2_FEATS=
    ZEROTH_KOREAN=/mnt/home/xungong-andr-1766e0/downloads/
    LRS2=
    JAVA=
    BENGALI=
    RU_OPEN_STT=/mnt/home/xungong-andr-1766e0/downloads/
    RUSLAN=/mnt/home/xungong-andr-1766e0/downloads/
    SIWIS=/mnt/home/xungong-andr-1766e0/downloads/
    SUNDA=
    CMU_INDIC=
    INDIC_SPEECH=
    JKAC=
    MUCS_SUBTASK1=/mnt/home/xungong-andr-1766e0/downloads/
    MUCS_SUBTASK2=/mnt/home/xungong-andr-1766e0/downloads/
    GAMAYUN=/mnt/home/xungong-andr-1766e0/downloads/
    IWSLT21LR=/mnt/home/xungong-andr-1766e0/downloads//iwslt21
    TOTONAC=/mnt/home/xungong-andr-1766e0/downloads/
    GOOGLEI18N=/mnt/home/xungong-andr-1766e0/downloads/
    MALAYALAM=

fi
