# bash local_split/run.sh --input_jsonl_raw data/part2_4/metadata.music.min_10.jsonl --expdir data/part2_4/full/novad-music.min_10 --yaml_path data/part2_4/full/data.yaml --name_prefix sft-part2_4-novad-music.min_10 --run_stages 0,4,6 --k 100000
# bash local_split/run.sh --input_jsonl_raw data/part2_4/metadata.music.min_0.max_10.jsonl --expdir data/part2_4/full/novad-music.min_0.max_10 --yaml_path data/part2_4/full/data.yaml --name_prefix sft-part2_4-novad-music.min_0.max_10 --run_stages 0,4,6 --k 100000
# bash local_split/run.sh --input_jsonl_raw data/part2_4/metadata.sound.min_0.max_7.jsonl --expdir data/part2_4/full/novad-sound.min_0.max_7 --yaml_path data/part2_4/full/data.yaml --name_prefix sft-part2_4-novad-sound.min_0.max_7 --run_stages 0,4,6 --k 100000
# bash local_split/run.sh --input_jsonl_raw data/part2_4/metadata.sound.min_7.max_10.jsonl --expdir data/part2_4/full/novad-sound.min_7.max_10 --yaml_path data/part2_4/full/data.yaml --name_prefix sft-part2_4-novad-sound.min_7.max_10 --run_stages 0,4,6 --k 100000
# bash local_split/run.sh --input_jsonl_raw data/part2_4/metadata.sound.min_10.jsonl --expdir data/part2_4/full/novad-sound.min_10 --yaml_path data/part2_4/full/data.yaml --name_prefix ;sft-part2_4-novad-sound.min_10 --run_stages 0,4,6 --k 100000
# bash local_split/run.sh --input_jsonl_raw data/part2_4/metadata.sound.min_10.jsonl --expdir data/part2_4/full/novad-sound.min_10 --yaml_path data/part2_4/full/data.yaml --name_prefix sft-part2_4-novad-sound.min_10 --run_stages 0,4,6 --k 100000
# bash local_split/run.sh --input_jsonl_raw data/part2_4/metadata.speech.min_3.max_5.jsonl --expdir data/part2_4/full/novad-speech.min_3.max_5 --yaml_path data/part2_4/full/data.yaml --name_prefix sft-part2_4-novad-speech.min_3.max_5 --run_stages 0,4,6 --k 100000
# bash local_split/run.sh --input_jsonl_raw data/part2_4/metadata.speech.min_5.max_8.jsonl --expdir data/part2_4/full/novad-speech.min_5.max_8 --yaml_path data/part2_4/full/data.yaml --name_prefix sft-part2_4-novad-speech.min_5.max_8 --run_stages 0,4,6 --k 100000
# bash local_split/run.sh --input_jsonl_raw data/part2_4/metadata.speech.min_8.max_20.jsonl --expdir data/part2_4/full/novad-speech.min_8.max_20 --yaml_path data/part2_4/full/data.yaml --name_prefix sft-part2_4-novad-speech.min_8.max_20 --run_stages 0,4,6 --k 100000
# bash local_split/run.sh --input_jsonl_raw data/part2_4/metadata.speech.min_20.max_25.jsonl --expdir data/part2_4/full/novad-speech.min_20.max_25 --yaml_path data/part2_4/full/data.yaml --name_prefix sft-part2_4-novad-speech.min_20.max_25 --run_stages 0,4,6 --k 100000


# bash local_split/run.sh --input_jsonl_raw data/part2_4/metadata.music.min_10.jsonl --expdir data/part2_4/full/vad-music.min_10 --yaml_path data/part2_4/full/data.yaml --name_prefix sft-part2_4-vad-music.min_10 --run_stages 1,2,4,6 --k 100000
# bash local_split/run.sh --input_jsonl_raw data/part2_4/metadata.sound.min_7.max_10.jsonl --expdir data/part2_4/full/vad-sound.min_7.max_10 --yaml_path data/part2_4/full/data.yaml --name_prefix sft-part2_4-vad-sound.min_7.max_10 --run_stages 1,2,4,6 --k 100000
# bash local_split/run.sh --input_jsonl_raw data/part2_4/metadata.sound.min_10.jsonl --expdir data/part2_4/full/vad-sound.min_10 --yaml_path data/part2_4/full/data.yaml --name_prefix sft-part2_4-vad-sound.min_10 --run_stages 1,2,4,6 --k 100000
# bash local_split/run.sh --input_jsonl_raw data/part2_4/metadata.speech.min_5.max_8.jsonl --expdir data/part2_4/full/vad-speech.min_8.max_20 --yaml_path data/part2_4/full/data.yaml --name_prefix sft-part2_4-vad-speech.min_8.max_20 --run_stages 1,2,4,6 --k 100000 # <=TODO
# bash local_split/run.sh --input_jsonl_raw data/part2_4/metadata.speech.min_20.max_25.jsonl --expdir data/part2_4/full/vad-speech.min_20.max_25 --yaml_path data/part2_4/full/data.yaml --name_prefix sft-part2_4-vad-speech.min_20.max_25 --run_stages 1,2,4,6 --k 100000
# bash local_split/run.sh --input_jsonl_raw data/part2_4/metadata.speech.min_25.jsonl --expdir data/part2_4/full/vad-speech.min_25 --yaml_path data/part2_4/full/data.yaml --name_prefix sft-part2_4-vad-speech.min_25 --run_stages 1,2,4,6 --k 100000